name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update and upgrade APT packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t iscanprint/springapp:2.2 .

      - name: Push Docker image
        run: |
          docker push iscanprint/springapp:2.2

      - name: Logout from Docker Hub
        run: docker logout
